# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca4b9f4db4ac582e3e53abb68f3be93cd424a276d9ce066d109b58fa3d74c5f69fb290b13c0eea8c2e4bc4bad1ec6f93c7e71f8ff45b67b8974c13142042d768

test:
  secret_key_base: 12cc2fd4c65141dc179a03421f02ccf45c86fba7faf8afe0e54ee4f6b84f2460d38f833ed7a6b0ec7473da80d464a19be21fe58237ddc693e78edd84d9e0c422

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
